# Generated by Django 3.0.4 on 2020-05-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalprojectmodel',
            old_name='likes_chocolate',
            new_name='likes_china',
        ),
        migrations.RenameField(
            model_name='finalprojectmodel',
            old_name='likes_vanilla',
            new_name='likes_usa',
        ),
    ]
