# Generated by Django 3.0.4 on 2020-05-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_auto_20200514_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalprojectmodel',
            old_name='likes_china',
            new_name='likes_China',
        ),
        migrations.RenameField(
            model_name='finalprojectmodel',
            old_name='likes_usa',
            new_name='likes_USA',
        ),
    ]
